import sys
import json
import time
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from medrag.hm_rag import HMRAGPipeline

def main():
    print("=============================================================")
    print("  ONCOLOGY Q&A PIPELINE RUNNER: RUNNING QUESTIONS & RECORDING")
    print("=============================================================")
    
    # Initialize Pipeline
    print("Loading Med42 RAG pipeline and SBERT model...")
    pipeline = HMRAGPipeline()
    
    # Load oncology questions dataset
    json_path = Path("/home/surdeep/Downloads/oncology_questions_100 (3).json")
    with open(json_path) as f:
        all_questions = json.load(f)
        
    print(f"Successfully loaded {len(all_questions)} questions from {json_path.name}")
    
    # Select target questions (Q100 to Q105)
    # Q100 is at index 99, Q101 at index 100, etc.
    target_indices = [99, 100, 101, 102, 103, 104]
    selected_questions = [all_questions[i] for i in target_indices]
    
    recorded_answers = []
    
    txt_output_path = PROJECT_ROOT / "oncology_answers_recorded.txt"
    json_output_path = PROJECT_ROOT / "oncology_answers_recorded.json"
    
    print(f"\nRunning RAG pipeline for {len(selected_questions)} selected questions...\n")
    
    with open(txt_output_path, "w") as txt_file:
        txt_file.write("=============================================================\n")
        txt_file.write("  RECORDED CLINICAL ANSWERS GENERATED BY LLAMA3-MED42-8B RAG\n")
        txt_file.write("=============================================================\n\n")
        
        for idx, item in enumerate(selected_questions, 1):
            q_id = item.get("id", f"Q{idx}")
            query = item.get("q", item.get("question", ""))
            gt = item.get("a", item.get("ground_truth", ""))
            
            print(f"[{idx}/{len(selected_questions)}] Running {q_id}...")
            print(f"  Query: {query[:80]}...")
            
            start_time = time.time()
            result = pipeline.run(query)
            latency = time.time() - start_time
            
            answer = result["answer"]
            context = result["context"]
            
            print(f"  Completed in {latency:.1f}s")
            print(f"  Answer: {answer[:100]}...\n")
            
            # Save data to record
            record_item = {
                "question_id": q_id,
                "question": query,
                "ground_truth": gt,
                "generated_answer": answer,
                "latency_s": round(latency, 2),
                "retrieved_sources": [
                    {
                        "source_file": c.get("source_file"),
                        "heading": c.get("heading"),
                        "content_preview": c.get("content", "")[:300]
                    }
                    for c in context
                ]
            }
            recorded_answers.append(record_item)
            
            # Write to TXT file live
            txt_file.write(f"-------------------------------------------------------------\n")
            txt_file.write(f"QUESTION ID: {q_id}\n")
            txt_file.write(f"QUESTION: {query}\n")
            txt_file.write(f"EXPECTED ANSWER (Ground Truth): {gt}\n")
            txt_file.write(f"LATENCY: {latency:.2f} seconds\n")
            txt_file.write(f"-------------------------------------------------------------\n")
            txt_file.write(f"GENERATED CLINICAL ANSWER:\n{answer}\n\n")
            txt_file.write(f"RELEVANT SOURCES RETRIEVED:\n")
            for c_idx, c in enumerate(context, 1):
                txt_file.write(f"  [{c_idx}] File: {c.get('source_file')}\n")
                txt_file.write(f"      Heading: {c.get('heading')}\n")
                txt_file.write(f"      Excerpt: {c.get('content')[:400].strip()}...\n\n")
            txt_file.write("\n\n")
            txt_file.flush() # Ensure it writes immediately
            
    # Write to JSON file
    with open(json_output_path, "w") as json_file:
        json.dump(recorded_answers, json_file, indent=2)
        
    print("=============================================================")
    print(f"  DONE! Answers recorded successfully in:")
    print(f"  - TXT Format: {txt_output_path}")
    print(f"  - JSON Format: {json_output_path}")
    print("=============================================================")

if __name__ == "__main__":
    main()
